### ISSUE TITLE
Exception: Curve does not contain point

### ISSUE THREAD

**Issue by micah** [prusnak/addrgen#12]
Hello,

I've taken the master public key from an electrum wallet and attempted to extract addresses from it:

```
irb(main):001:0> require 'bitcoin-addrgen'
=> true
irb(main):002:0> master_public_key = "xpub661MyMwAqRbcFTm4eJJRB4SvWGWGj8UC2Vajs7arYz4cJfDJS8nYi1pY51FDu65Z2JNFtqj4ZqxdceNueEobSkkNqGjn7aKXTv9yD6Yfycm"
=> "xpub661MyMwAqRbcFTm4eJJRB4SvWGWGj8UC2Vajs7arYz4cJfDJS8nYi1pY51FDu65Z2JNFtqj4ZqxdceNueEobSkkNqGjn7aKXTv9yD6Yfycm"
irb(main):003:0> first_ten_addresses = 10.times.collect do |address_index|
irb(main):004:1*   BitcoinAddrgen.generate_public_address(master_public_key, address_index)
irb(main):005:1> end
Exception: Curve does not contain point
	from /var/lib/gems/2.3.0/gems/bitcoin-addrgen-0.1.0/lib/bitcoin_addrgen/addrgen.rb:191:in `initialize'
	from /var/lib/gems/2.3.0/gems/bitcoin-addrgen-0.1.0/lib/bitcoin_addrgen/addrgen.rb:311:in `new'
	from /var/lib/gems/2.3.0/gems/bitcoin-addrgen-0.1.0/lib/bitcoin_addrgen/addrgen.rb:311:in `addr_from_mpk'
	from /var/lib/gems/2.3.0/gems/bitcoin-addrgen-0.1.0/lib/bitcoin-addrgen.rb:7:in `generate_public_address'
	from (irb):4:in `block in irb_binding'
	from (irb):3:in `times'
	from (irb):3:in `each'
	from (irb):3:in `collect'
	from (irb):3
	from /usr/bin/irb:11:in `<main>'
irb(main):006:0>
```

**Comment by prusnak** [comment]
addrgen does not support xpubs

use this if you want to use xpub: https://github.com/prusnak/bip32utils

**Comment by micah** [comment]
Pavol Rusnak <notifications@github.com> writes:

> addrgen does not support xpubs
>
> use this if you want to use xpub: https://github.com/prusnak/bip32utils

unfortunately, that is python only, i need a ruby library

**Comment by prusnak** [comment]
google for "bip32 ruby" then
